services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/employee_db_employee.sql:/docker-entrypoint-initdb.d/employee_db_employee.sql

  app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_DB: employee_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"

volumes:
  dbdata: